import express from "express";
import fetch from "node-fetch";
import { create } from "xmlbuilder2";
import pkg from "fast-xml-parser";
const { parse } = pkg;

const app = express();
const cache = new Map();
const CACHE_DURATION = 60 * 60 * 1000; // 1小时缓存

app.get("/", (req, res) => {
  res.send("✅ YouTube RSS Proxy is running. Use /api/rss?channel_id=...");
});

app.get("/api/rss", async (req, res) => {
  const channelId = req.query.channel_id;
  if (!channelId) return res.status(400).send("❌ Missing channel_id parameter");

  const cached = cache.get(channelId);
  const now = Date.now();
  if (cached && now - cached.timestamp < CACHE_DURATION) {
    res.type("application/xml").send(cached.data);
    return;
  }

  try {
    const feedUrl = `https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`;
    const response = await fetch(feedUrl);
    if (!response.ok) throw new Error(`Fetch failed: ${response.status}`);

    const text = await response.text();
    const parsed = parse(text, { ignoreAttributes: false });
    const feed = parsed.feed;

    const rss = create({ version: "1.0", encoding: "UTF-8" })
      .ele("rss", { version: "2.0", "xmlns:media": "http://search.yahoo.com/mrss/" })
      .ele("channel")
      .ele("title").txt(feed.title).up()
      .ele("link").txt(`https://www.youtube.com/channel/${channelId}`).up()
      .ele("description").txt("Generated by Node.js YouTube RSS Proxy").up();

    const entries = Array.isArray(feed.entry) ? feed.entry : [feed.entry];
    entries.forEach((video) => {
      const videoId = video["yt:videoId"];
      const item = rss.ele("item");
      item.ele("title").txt(video.title).up();
      item.ele("link").txt(video.link["@_href"]).up();
      item.ele("pubDate").txt(new Date(video.published).toUTCString()).up();
      item.ele("description").dat(video["media:group"]["media:description"]).up();
      item.ele("media:thumbnail", { url: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg` }).up();
      item.up();
    });

    const xmlOutput = rss.end({ prettyPrint: true });
    cache.set(channelId, { data: xmlOutput, timestamp: now });
    res.type("application/xml").send(xmlOutput);

  } catch (err) {
    console.error("❌ Fetch or parse error:", err);
    res.status(500).send("❌ Failed to fetch or parse feed");
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`🚀 Server running on port ${PORT}`));
