import express from "express";
import fetch from "node-fetch";
import { create } from "xmlbuilder2";
import { XMLParser } from "fast-xml-parser";

// fast-xml-parser v4 exports XMLParser class. Instantiate once with
// options (keep attributeNamePrefix to "@_" so existing code that
// references "@_href" continues to work).
const parser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: "@_" });

const app = express();
const cache = new Map();
const CACHE_DURATION = 60 * 60 * 1000;

// --- 辅助函数：根据 YouTube 频道 XML 数据生成 RSS 2.0 格式 ---
function generateRssFromFeed(feed, channelId, title, description = "Generated by Node.js YouTube RSS Proxy") {
  const rss = create({ version: "1.0", encoding: "UTF-8" })
    .ele("rss", {
      version: "2.0",
      "xmlns:media": "http://search.yahoo.com/mrss/"
    })
    .ele("channel")
    .ele("title").txt(title).up()
    .ele("link").txt(`https://www.youtube.com/channel/${channelId}`).up()
    .ele("description").txt(description).up();

  // 确保 feed.entry 是数组，即使只有一个 item
  const entries = Array.isArray(feed.entry) ? feed.entry : (feed.entry ? [feed.entry] : []);
  entries.forEach((video) => {
    const videoId = video["yt:videoId"];
    const item = rss.ele("item");
    item.ele("title").txt(video.title).up();
    // 使用 video.link["@_href"] 作为链接
    item.ele("link").txt(video.link["@_href"]).up();
    item.ele("guid").txt(videoId).up();
    item.ele("pubDate").txt(new Date(video.published).toUTCString()).up();
    item.ele("description").dat(video["media:group"]["media:description"]).up();
    // Add thumbnail if available
    const thumbnail = video["media:group"]["media:thumbnail"];
    if (thumbnail && thumbnail["@_url"]) {
      item.ele("media:thumbnail", { url: thumbnail["@_url"] }).up();
    }
    item.up();
  });

  return rss.end({ prettyPrint: true });
}

// --- 辅助函数：获取并解析 YouTube XML 订阅源 ---
async function fetchAndParseFeed(feedUrl) {
  const response = await fetch(feedUrl);
  if (!response.ok) throw new Error(`Fetch failed with status: ${response.status} for URL: ${feedUrl}`);

  const text = await response.text();
  const parsed = parser.parse(text);
  return parsed.feed;
}


app.get("/", (req, res) => {
  res.send("✅ YouTube RSS Proxy is running. Use /api/rss?channel_id=... or /api/user/@username");
});

// --- 现有路由：通过 channel_id 获取 RSS ---
app.get("/api/rss", async (req, res) => {
  const channelId = req.query.channel_id;
  if (!channelId) return res.status(400).send("❌ Missing channel_id parameter");

  const cacheKey = `channel:${channelId}`;
  const cached = cache.get(cacheKey);
  const now = Date.now();
  if (cached && now - cached.timestamp < CACHE_DURATION) {
    res.type("application/xml").send(cached.data);
    return;
  }

  try {
    const feedUrl = `https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`;
    const feed = await fetchAndParseFeed(feedUrl);
    
    // 使用辅助函数生成 RSS
    const xmlOutput = generateRssFromFeed(feed, channelId, feed.title);
    
    cache.set(cacheKey, { data: xmlOutput, timestamp: now });
    res.type("application/xml").send(xmlOutput);

  } catch (err) {
    console.error("❌ Fetch or parse error:", err);
    res.status(500).send("❌ Failed to fetch or parse feed");
  }
});


// --- 新增路由：通过用户句柄 (username) 获取 RSS ---
// 注意：原代码中的 /user/:username/:routeParams? 结构在 Express 中通常简化为 /user/:username
// 我们通过 req.query 来接收参数，而不是 /:routeParams?
app.get("/api/user/:username", async (req, res) => {
  const username = req.params.username;
  if (!username) return res.status(400).send("❌ Missing username parameter");

  // --- 参数解析逻辑 (根据第一个代码块) ---
  // Express 使用 req.query 获取查询字符串参数，如 ?embed=1&filterShorts=false
  
  // 原代码的 `embed` 逻辑: const embed = !params.get('embed');
  // 如果 URL 中有 `embed` 参数（如 ?embed=1），则 embed 为 false (不嵌入)。
  // 如果 URL 中没有 `embed` 参数，则 embed 为 true (嵌入)。
  // 在 RSS 代理中，通常不需要这个参数，但我们解析它。
  const embed = !req.query.embed; 

  // 原代码的 `filterShorts` 逻辑:
  // const filterShorts = filterShortsStr === null || filterShortsStr === '' || filterShortsStr === 'true';
  // 仅在 filterShorts 为 'false' 或其他 falsy 值时，才不过滤 Shorts。默认过滤。
  const filterShortsStr = req.query.filterShorts;
  const filterShorts = filterShortsStr === undefined || filterShortsStr === '' || filterShortsStr === 'true';
  
  // 注意：原代码的 handler 函数使用了 getDataByUsernameYoutubei 和 getDataByUsernameGoogle，
  // 它们是调用 API 获取数据的抽象。在这个 Express 代理中，我们**无法直接访问**这些内部 API。
  // **解决方案：** // 1. **最直接的模仿 (不准确):** 尝试用 `username` 直接构造一个 YouTube XML 订阅源 URL。
  //    遗憾的是，YouTube 的 /feeds/videos.xml **只支持 `channel_id` 或 `user` (legacy)。**
  //    **不直接支持** `username` (用户句柄，如 @JFlaMusic)。
  // 2. **需要额外的 API 步骤 (更准确):** 必须先通过 YouTube Data API (v3) 或解析网页，
  //    **将 `username` 转换为 `channel_id`**，然后才能使用 `/feeds/videos.xml`。
  //    由于 Express 代理中没有现成的 `getDataByUsernameYoutubei` 或 `getDataByUsernameGoogle` 函数，
  //    我们将使用 **最直接的模仿** 方式，**假设** 存在一个 `username` 版本的 XML 订阅源 URL（虽然 YouTube 官方没有）。

  const cacheKey = `user:${username}:${filterShorts}:${embed}`;
  const cached = cache.get(cacheKey);
  const now = Date.now();
  if (cached && now - cached.timestamp < CACHE_DURATION) {
    res.type("application/xml").send(cached.data);
    return;
  }

  try {
    // ⚠️ 警告：这是对第一个代码块功能的**不完整**模仿，
    // 因为 YouTube XML 订阅源不直接支持 `@username`。
    // 实际实现需要一个额外的步骤来查找 `channel_id`。
    // 我们在此假设一个 **`/feeds/videos.xml?handle=`** 的理想情况。
    const feedUrl = `https://www.youtube.com/feeds/videos.xml?handle=${username}`;
    
    // **理想情况下，这里应该调用第一个代码块中的 `callApi` 逻辑来获取数据**
    // 如下所示：
    /*
    const data = await callApi({
        googleApi: getDataByUsernameGoogle,
        youtubeiApi: getDataByUsernameYoutubei,
        params: { username, embed, filterShorts, isJsonFeed: false },
    });
    // 然后将 data 转换为 XML
    */

    // --- 临时替代方案：直接尝试获取 feedUrl ---
    const feed = await fetchAndParseFeed(feedUrl);
    
    // 假设我们能从 feed 中获取到真正的 channelId
    const inferredChannelId = feed.link?.["@_href"]?.match(/channel\/(.+)/)?.[1] || 'UNKNOWN_ID';

    // 假设 `feed` 数据结构包含所有视频信息，但我们**没有实现** `filterShorts` 逻辑。
    // **注意：** 这里的 `generateRssFromFeed` 还没有实现 `filterShorts` 过滤短片的功能。
    const xmlOutput = generateRssFromFeed(feed, inferredChannelId, feed.title);
    
    cache.set(cacheKey, { data: xmlOutput, timestamp: now });
    res.type("application/xml").send(xmlOutput);

  } catch (err) {
    console.error(`❌ Fetch or parse error for user ${username}:`, err);
    // 对于 @username 的情况，404 可能是正常的，因为 YouTube 不支持此 URL 结构
    res.status(500).send(`❌ Failed to fetch or parse feed for user ${username}. (Note: This function requires converting @username to channel_id, which is not implemented here.)`);
  }
});


const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`🚀 Server running on port ${PORT}`));
