import express from "express";
import axios from "axios";
import { create } from "xmlbuilder2";

const app = express();
const PORT = process.env.PORT || 10000;

// RSS 生成逻辑
app.get("/", async (req, res) => {
  const channelId = req.query.channel_id;
  if (!channelId) {
    return res.send("请在 URL 后加上 ?channel_id=UCxxxxxx");
  }

  try {
    const rssUrl = `https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`;
    const { data } = await axios.get(rssUrl);

    const regex = /<entry>([\s\S]*?)<\/entry>/g;
    const entries = [...data.matchAll(regex)];

    const feed = create({ version: "1.0", encoding: "UTF-8" })
      .ele("rss", {
        version: "2.0",
        "xmlns:media": "http://search.yahoo.com/mrss/"
      })
      .ele("channel")
      .ele("title")
      .txt(`Custom YouTube RSS for ${channelId}`)
      .up()
      .ele("link")
      .txt(`https://www.youtube.com/channel/${channelId}`)
      .up()
      .ele("description")
      .txt(`Feed generated by Node.js RSS builder`)
      .up();

    for (const entry of entries) {
      const id = entry[1].match(/<yt:videoId>(.*?)<\/yt:videoId>/)?.[1];
      const title = entry[1].match(/<title>(.*?)<\/title>/)?.[1];
      const published = entry[1].match(/<published>(.*?)<\/published>/)?.[1];

      const link = `https://www.youtube.com/watch?v=${id}`;
      const thumb = `https://img.youtube.com/vi/${id}/0.jpg`;
      const embed = `https://www.youtube-nocookie.com/embed/${id}`;

      const item = feed.ele("item");
      item.ele("title").txt(title).up();
      item.ele("link").txt(link).up();
      item.ele("pubDate").txt(new Date(published).toUTCString()).up();
      item.ele("guid", { isPermaLink: "false" }).txt(id).up();
      item.ele("media:thumbnail", { url: thumb }).up();
      item.ele("media:content", { url: embed, type: "text/html" }).up();
      item.up();
    }

    const xml = feed.end({ prettyPrint: true });
    res.set("Content-Type", "application/xml");
    res.send(xml);
  } catch (err) {
    res.status(500).send("获取 RSS 时出错：" + err.message);
  }
});

app.listen(PORT, () => console.log(`Server running on port ${PORT}`));